# vectordb_client/exceptions.py
class VectorDBError(Exception): ...
class NotFound(VectorDBError): ...
class Conflict(VectorDBError): ...
class BadRequest(VectorDBError): ...
class TransportError(VectorDBError): ...
class ServerError(VectorDBError): ...
